security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_USER:      ROLE_USER
        ROLE_VENDEUR:   [ROLE_USER, ROLE_VENDEUR]
        ROLE_ADMIN: [ROLE_USER, ROLE_VENDEUR, ROLE_ADMIN]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        admin_secured_area:
            pattern:    ^/
            anonymous: ~
            provider: user_db
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
            logout:
                path:   _demo_logout
                target: _demo
 
    providers:
        user_db:
            entity: { class: Odysseus\Entity\User, property: mail }

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
