parameters:
#    odysseus_user.example.class: Odysseus\Bundle\UserBundle\Example

services:
#    odysseus_user.example:
#        class: %odysseus_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
